
name: Validate Chain Files

on:
  pull_request:
    paths:
      - 'constants/additionalChainRegistry/*.js'
      - 'constants/extraRpcs.js'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100

      - name: Set changed files
        id: files
        run: |
          echo "FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep 'constants/additionalChainRegistry/' || true)" >> $GITHUB_ENV
          echo "EXTRA_RPC_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep 'constants/extraRpcs.js' || true)" >> $GITHUB_ENV

      - name: Validate chain and extracRpcs files
        run: |
          if [ -z "$FILES_CHANGED" ] || [ -z "$EXTRA_RPC_CHANGED" ]; then
            echo "No relevant files changed."
            exit 0
          fi
          npm ci
          ONLY_LIST_FILE=true npm run build
          node .github/scripts/validate-chain-files.js
          
        env:
          FILES_CHANGED: ${{ env.FILES_CHANGED }}
          EXTRA_RPC_CHANGED: ${{ env.EXTRA_RPC_CHANGED }}

      - name: Comment on PR if validation fails
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
               + "\n\nError message:\n```\n${process.env.GITHUB_STEP_SUMMARY || 'See workflow logs for details.'}\n```"})
